### ISSUE TITLE
Rotary Encoder sizing

### ISSUE THREAD

**Issue by abatkin** [Karolis92/pico-macropad#1]
I'm wondering if you could provide additional details about the rotary encoder you used, for example if it a specific "type" or what key attributes and/or dimensions I should be looking for. I have a couple rotary encoders and the backsides look quite different from what I see in your photos, and from the manufacturer datasheets, I don't see anything with dimensions that look like they would fit in the case.

Thanks!

**Comment by Karolis92** [comment]
Pad base has 6.9mm hole. Knob fits on 5.98 shaft.
Actual encoder model: [EC12D1524403](https://tech.alpsalpine.com/e/products/detail/EC12D1524403/)
Code uses [rotaryio](https://docs.circuitpython.org/en/latest/shared-bindings/rotaryio/index.html) so refer to it's documentation for your specific encoder.

**Comment by abatkin** [comment]
Awesome, that is very helpful. Thank you!
